// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPnW5U9c0XkjBeR5QzBt2oqpngKkq9qyM',
    appId: '1:615843292102:web:30719c4956f32f67a388c7',
    messagingSenderId: '615843292102',
    projectId: 'newsblog-6a787',
    authDomain: 'newsblog-6a787.firebaseapp.com',
    storageBucket: 'newsblog-6a787.firebasestorage.app',
    measurementId: 'G-GVYWNYLTE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDONnUKHLbKMs_sJNC_Rx7eNnyFFgKG8Bc',
    appId: '1:615843292102:android:3aeb0ec965a0d625a388c7',
    messagingSenderId: '615843292102',
    projectId: 'newsblog-6a787',
    storageBucket: 'newsblog-6a787.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALYnL5J_uCsa9nYivQ-549G1xs6Y3wnT4',
    appId: '1:615843292102:ios:eeede5d7f4c20fe7a388c7',
    messagingSenderId: '615843292102',
    projectId: 'newsblog-6a787',
    storageBucket: 'newsblog-6a787.firebasestorage.app',
    androidClientId: '615843292102-c4msa6opouiko08j0s0hahq7nhj98aov.apps.googleusercontent.com',
    iosClientId: '615843292102-dgtsfo9uum2177r7qm2phr9tu71k0b46.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsblog',
  );

}